//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldQuakeViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bouyomichan_Enable {
            get {
                return ((bool)(this["Bouyomichan_Enable"]));
            }
            set {
                this["Bouyomichan_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string Bouyomichan_Host {
            get {
                return ((string)(this["Bouyomichan_Host"]));
            }
            set {
                this["Bouyomichan_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50001")]
        public int Bouyomichan_Port {
            get {
                return ((int)(this["Bouyomichan_Port"]));
            }
            set {
                this["Bouyomichan_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short Bouyomichan_Voice {
            get {
                return ((short)(this["Bouyomichan_Voice"]));
            }
            set {
                this["Bouyomichan_Voice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public short Bouyomichan_Speed {
            get {
                return ((short)(this["Bouyomichan_Speed"]));
            }
            set {
                this["Bouyomichan_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public short Bouyomichan_Tone {
            get {
                return ((short)(this["Bouyomichan_Tone"]));
            }
            set {
                this["Bouyomichan_Tone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public short Bouyomichan_Volume {
            get {
                return ((short)(this["Bouyomichan_Volume"]));
            }
            set {
                this["Bouyomichan_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tweet_Enable {
            get {
                return ((bool)(this["Tweet_Enable"]));
            }
            set {
                this["Tweet_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tweet_ConsumerKey {
            get {
                return ((string)(this["Tweet_ConsumerKey"]));
            }
            set {
                this["Tweet_ConsumerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tweet_ConsumerSecret {
            get {
                return ((string)(this["Tweet_ConsumerSecret"]));
            }
            set {
                this["Tweet_ConsumerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tweet_AccessToken {
            get {
                return ((string)(this["Tweet_AccessToken"]));
            }
            set {
                this["Tweet_AccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tweet_AccessSecret {
            get {
                return ((string)(this["Tweet_AccessSecret"]));
            }
            set {
                this["Tweet_AccessSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double Tweet_LowerMagnitudeLimit {
            get {
                return ((double)(this["Tweet_LowerMagnitudeLimit"]));
            }
            set {
                this["Tweet_LowerMagnitudeLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Display_HideHistory {
            get {
                return ((bool)(this["Display_HideHistory"]));
            }
            set {
                this["Display_HideHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Display_HideHistoryMap {
            get {
                return ((bool)(this["Display_HideHistoryMap"]));
            }
            set {
                this["Display_HideHistoryMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Text_LatLonDecimal {
            get {
                return ((bool)(this["Text_LatLonDecimal"]));
            }
            set {
                this["Text_LatLonDecimal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Tweet_LowerMMILimit {
            get {
                return ((double)(this["Tweet_LowerMMILimit"]));
            }
            set {
                this["Tweet_LowerMMILimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Bouyomichan_LowerMagnitudeLimit {
            get {
                return ((double)(this["Bouyomichan_LowerMagnitudeLimit"]));
            }
            set {
                this["Bouyomichan_LowerMagnitudeLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Bouyomichan_LowerMMILimit {
            get {
                return ((double)(this["Bouyomichan_LowerMMILimit"]));
            }
            set {
                this["Bouyomichan_LowerMMILimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Socket_Host {
            get {
                return ((string)(this["Socket_Host"]));
            }
            set {
                this["Socket_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Socket_Port {
            get {
                return ((int)(this["Socket_Port"]));
            }
            set {
                this["Socket_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Sound_45_Enable {
            get {
                return ((bool)(this["Sound_45_Enable"]));
            }
            set {
                this["Sound_45_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Sound_60_Enable {
            get {
                return ((bool)(this["Sound_60_Enable"]));
            }
            set {
                this["Sound_60_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Sound_80_Enable {
            get {
                return ((bool)(this["Sound_80_Enable"]));
            }
            set {
                this["Sound_80_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Sound_Updt_Enable {
            get {
                return ((bool)(this["Sound_Updt_Enable"]));
            }
            set {
                this["Sound_Updt_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Socket_Enable {
            get {
                return ((bool)(this["Socket_Enable"]));
            }
            set {
                this["Socket_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Text}")]
        public string Socket_Text {
            get {
                return ((string)(this["Socket_Text"]));
            }
            set {
                this["Socket_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bouyomichan_Lower_And {
            get {
                return ((bool)(this["Bouyomichan_Lower_And"]));
            }
            set {
                this["Bouyomichan_Lower_And"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tweet_Lower_And {
            get {
                return ((bool)(this["Tweet_Lower_And"]));
            }
            set {
                this["Tweet_Lower_And"] = value;
            }
        }
    }
}
